/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
USE DataWarehouse;

-- Find total customers by countries
SELECT  
	country , 
	COUNT(customer_id) AS  total_cutomers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_cutomers DESC;

-- Find total customers by gender
SELECT  
	gender , 
	COUNT(customer_id) AS  total_cutomers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_cutomers DESC;

-- Find total products by category
SELECT 
	category, 
	COUNT(product_id) AS total_products 
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT 
	category, 
	AVG(cost) AS average_costs
FROM GOLD.dim_products
GROUP BY category
ORDER BY AVG(cost)  DESC;

-- What is the total revenue generated for each category?
SELECT 
	dp.category, 
	SUM(fs.sales_amount) AS total_sales
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp
	ON FS.product_key = DP.product_key
GROUP BY dp.category
ORDER BY total_sales DESC;

-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
